export { Mod } from "./src/mod";
export type { ModInfo } from "./src/mod";
export { BaseModGenerator } from "./src/mod_generator";
export { BedrockModGenerator } from "./src/bedrock/bedrock_mod_generator";
export { FabricModGenerator } from "./src/fabric/ModGenerator";
export { type Item } from "./src/item";
export { type MinecraftLanguage } from "./src/language";
export { getItemFullID } from "./src/item";
export { type FabricSupportedJavaVersion } from "./src/fabric/modSettings";
export { type Translation, type Version } from "./src/mod";
export { type ToolItemComponent } from "./src/item_components";