export { Mod } from "./src/mod";
export type { ModInfo } from "./src/mod";
export { BaseModGenerator } from "./src/mod_generator";
export { BedrockModGenerator } from "./src/bedrock/bedrock_mod_generator";
export { FabricModGenerator } from "./src/fabric/ModGenerator";
export { type ItemProperties } from "./src/item";
export { Item } from "./src/item";
export { type Identifiable } from "./src/identifier";
export { Identifier } from "./src/identifier";
export { type Registry, GenericRegistry, PlatformRegistry ,IdentifiableRegistry, IdentifiablePlatformRegistry } from "./src/registry";
export { type MinecraftLanguage } from "./src/language";
export { type FabricSupportedJavaVersion } from "./src/fabric/modSettings";
export { type Translation, type Version } from "./src/mod";